sudo: false
language: java

jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
  - oraclejdk8

install:
  - git clone https://github.com/borismarin/expr-parser.git
  - cd expr-parser
  - mvn install
  - cd $TRAVIS_BUILD_DIR 


 


